### ISSUE TITLE
Feil styling på tekstfelter

### ISSUE THREAD

**Issue by sirasjad** [kodesonen/nettside-v2#110]
Tekstfelt får ikke riktig styling hvis jeg ikke oppgir "type". Altså hvis jeg setter type til "text" eller "password" så fungerer det fint. Jeg definerer type i C# istedenfor HTML og lar ASP.NET håndtere dette. Derfor trenger jeg ikke å bestemme type i HTML koden.

Dette funker:
`<input type="text" asp-for="Email" placeholder="Skriv inn din e-post adresse">`

Dette funker ikke:
`<input asp-for="Email" placeholder="Skriv inn din e-post adresse">`

Er dette en kjapp fiks i CSS?

![image](https://user-images.githubusercontent.com/8083228/112871979-22fc1b00-90c0-11eb-892c-5aed69644325.png)

**Comment by sirasjad** [comment]
Rettelse: Dette gjelder kun når type er "email". Jeg ser at input fields som bruker type "text" eller "password" fungerer fint, men type "email" får feil styling.

**Comment by Danielskry** [comment]
Ser på dette nå!
