### ISSUE TITLE
Bilde til Om Oss

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside-v2#94]
Trenger nok et bilde til Om Oss under "Hvordan vi jobber"

**Comment by sirasjad** [comment]
@Danielskry Ble vi ikke enig om å flytte "Hvordan vi jobber" til "Prosjekter"-siden, der vi skriver litt om webteamet og de andre prosjektene vi driver? Altså beskrive CI/CD workflowen, hvordan vi utvikler og tester underveis, osv.

**Comment by Danielskry** [comment]
Jo det høres riktig ut @sirasjad, da skal det nok være sånn. Fjerner den delen av Om Oss siden!
