### ISSUE TITLE
Komprimering av promotion bildet på forsiden

### ISSUE THREAD

**Issue by Danielskry** [kodesonen/nettside-v2#96]
Bildet lastes inn for treigt.

**Comment by sirasjad** [comment]
@Danielskry Tror vi kan utsette image compression til neste release. Det er mye som kan forbedres med tanke på performace, blant annet Entity Framework queries og måten vi laster inn data. Jeg tror nok at vi har mye tid å spare her, sammenlignet med komprimerte bilder. 

Merk at image compression (eller caching egentlig) håndteres automatisk av Cloudflare når DNS-en flyttes over dit. Isåfall tror jeg komprimerte bilder har veldig liten effekt med tanke på tidssparing.
