### ISSUE TITLE
Auto-wrap kursinnhold på profilsiden

### ISSUE THREAD

**Issue by sirasjad** [kodesonen/nettside-v2#99]
Dette fungerer akkurat nå, men er håndtert i backend og ikke en god løsning. Har satt character limit på 750, men det gjelder HTML koden og ikke kun tekstinnholdet. Det vil si at hvis character 749 er en unclosed HTML tag så vil det skape problemer. 

Bedre å håndtere dette i frontend med fixed height? 

Slik ser det ut akkurat nå. I dette tilfellet ser alt bra ut, men hvis vi f.eks har et bilde på slutten og ikke får closa HTML tag-en så vil det oppstå bugs.

![image](https://user-images.githubusercontent.com/8083228/112738731-f03e0f80-8f65-11eb-8aeb-70a20784bb58.png)

Slik håndteres det i kode. Ikke en god løsning altså:
![image](https://user-images.githubusercontent.com/8083228/112738899-43fd2880-8f67-11eb-87f9-4436dcf2e261.png)

**Comment by sirasjad** [comment]
@Danielskry Tanker her?

**Comment by Danielskry** [comment]
Veldig godt tenkt! Jeg har fikset det nå!
